name: driverApp

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^7.0.1
  provider: ^6.1.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/profile_picture.png